### PR TITLE
Remove 'fw'

### PR DESCRIPTION
**Pull request by rrthomas**
- Remove 'fw' firewall detection methods
- Note that we've added support for DNSExit API v2

### CODE REVIEW

**Comment by rrthomas** [comment]
Note that this PR breaks backwards compatibility. I suggest that the next release should indeed break backwards compatibility (and be version 4, respecting semver). In some cases it will make sense to retain deprecated options (e.g. the non-IPvX-specific methods, which default to v4 at present); in others, where functionality is removed, the user will want to know that it has been removed, as here.

**Comment by LenardHess** [comment]
> Instead of outright removing it, lets add example script support for it - similar to [the FritzBox example](https://github.com/rrthomas/ddclient/blob/78bcc11244cf9d2d78746cb1dd8db803731a0bd8/sample-get-ip-from-fritzbox).

That's fine. I am doubtful that much of the existing functionality is used, so I'm not really prepared to do this work myself.

> The existing [firmware configurations](https://github.com/rrthomas/ddclient/blob/78bcc11244cf9d2d78746cb1dd8db803731a0bd8/ddclient.in#L112) should then be moved out to a separate table (i.e. in the script or the README) with the relevant disclaimers that we aren't promising maintenance on URLs/skip values for these

Sure, I agree that outsourcing this sort of configuration in general is a good idea, and it should have "contrib"/"extra" status.

(I will just reassure you here that I don't plan to impose any backwards-compatibility breakage unilaterally. I think there is scope to remove a lot of functionality, as you'll see on the `rrthomas-downsize` branch, but I'm sensitive to what others use. I prefer to remove a lot of functionality and concentrate on the core to reduce the future maintenance burden.)

**Comment by LenardHess** [comment]
And on the topic of backwards compatibility:
I would prefer to do a backwards compatible release (basically just fix regressions and then release). Then we make our backwards-incompatible changes in major version 4 as you said.

This way we can first iron out the release process, check in with any downstream maintainers etc. before breaking compatibility

**Comment by rrthomas** [comment]
> And on the topic of backwards compatibility: I would prefer to do a backwards compatible release (basically just fix regressions and then release). Then we make our backwards-incompatible changes in major version 4 as you said.

Yes, definitely a good idea.

**Comment by rrthomas** [comment]
I'll close this PR and keep the `rrthomas-downsize` branch for straight up code removal (in logical chunks).

These commits can also be used as the basis of work to "outsource" code in a backwards-compatible way, as I think I have identified the code to be factored out.

**Pull request closed without merging**
